# Generated by Django 4.1.5 on 2023-01-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_departamento_codigo_alter_empleado_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='presupuesto',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nif',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
