# Generated by Django 4.1.5 on 2023-01-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_departamento_presupuesto_alter_empleado_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
